# Core-element of MC Server Soft.
# Provides real-time diagnostics and server telemetry.
# This file will be used by mcss, please don't alter this file unless... you're a rebel.

# URL of the mcss internal webserver
url: "{0}"

# The GUID of the mcss server
serverGUID: "{1}"

# Enable or disable debugging of mcss requests
debug: false